checks:
  php:
    code_rating: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
tools:
  external_code_coverage:
    timeout: 600
    runs: 3
  php_code_coverage: false
  php_code_sniffer:
    config:
      standard: PSR2
    filter:
      paths: ['src']
  php_loc:
    enabled: true
    excluded_dirs: [bin, stub, vendor, tests]
  php_cpd:
    enabled: true
    excluded_dirs: [bin, stub, vendor, tests]
