language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: 7.0
before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-lowest
  - 'curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@composer.lock'
script:
  - vendor/bin/phpcs --report-full --standard=PSR2 src
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-text --verbose --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
